name: Build and Deploy Sphinx Documentation
# Workflow de construction et de déploiement de la documentation Sphinx

on:
  push:
    branches: 
      - '**'
  #pull_request:
    #types:
      #- closed

jobs:
  if_merged:
    #if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Installation des dependences
      run: |
        python -m pip install --upgrade pip
        pip install sphinx

    - name: Build Sphinx documentation
      continue-on-error: true
      run: |
        sphinx-build -M html ./docs/source ./build --fail-on-warning

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
      with:
        publish_branch: gh-pages
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: /build/html
        force_orphan: true