# Workflow de test et de nettoyage du code

name: CLI_TASK_MANAGER

on:
  push:
    branches: 
      - '**'
  pull_request:
    branches:
      - '**'

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Installation des dependences
      run: |
        python -m pip install --upgrade pip
        pip install pylint pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with pylint
      continue-on-error: true
      run: |
       pylint source
    - name: Test with pytest
      run: |
        pytest
