# Workflow de test et de nettoyage du code

name: CLI_TASK_MANAGER

on:
  push:
    branches: 
      - '**'
  pull_request:
    branches:
      - '**'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Affichage de la version de python
      run: |
        python -c "import sys; print(sys.version)"
    - name: Installation des dependences
      run: |
        python -m pip install --upgrade pip
        pip install pylint pytest coverage
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint avec pylint
      continue-on-error: true
      run: |
       pylint source
    - name: Test avec pytest (et mesure du coverage)
      run: |
        coverage run -m pytest
        coverage report -m
